Allow alternative_locales to be disabled in config
statamic/seo-pro pull request #167
Opened 2021-04-02 15:28 UTC by CiiDyR

This allows alternate_locales to be disabled for meta tag generation.
This might be useful for people that are using the Multi-Site system for purposes other than alternate locales such as a different brand (think tenancy-like usage). 

Even the docs mention this as a valid use-case for the multi-site system: https://statamic.dev/multi-site#overview

Happy to adjust the PR as needed :)

Maybe @jesseleite can take a look?

2021-04-09 10:01 UTC, CiiDyR commented
@jesseleite @jasonvarga Any chance to review and merge this soon? :-)

2021-04-09 16:02 UTC, jesseleite commented
@CiiDyR Will give this a proper review and test when I can, thank you for your PR, and your for patience! ❤️

2021-04-15 08:33 UTC, malte-bue commented
Any updates on this? @jesseleite

2021-05-03 19:08 UTC, jesseleite requested changes

2021-05-03 19:08 UTC, jesseleite commented on config/seo-pro.php
> +    ],
This is a great PR 👍

We had a chat about it though, and would ask that you refactor the config from this:

```php
'alternate_locales' => [
    'enabled_in_meta' => true,
],
```

To this:

```php
'alternate_locales' => true,
```

2021-05-03 19:36 UTC, merged

2021-05-03 19:40 UTC, jesseleite commented
Great PR, thank you 👍  Just tweaked [the config a bit here](https://github.com/statamic/seo-pro/commit/4088a87c26954d373977ed62a5a40f0132c6abc7).

2021-05-04 07:01 UTC, CiiDyR commented
Thanks for merging @jesseleite  :+1: